apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-{APP_NAME}
  labels:
    tier: backend
data:
  .env : | 
    SERVER_PORT=1323
    ENV={ENVIRONMENT}
    #config
    DB_DRIVER=postgres
    DB_HOST={POSTGRES_HOST}
    DB_PORT=5432
    DB_USER={POSTGRES_USER}
    DB_PASSWORD={POSTGRES_PASS}
    DB_DATABASE={POSTGRES_DB}

    CLICKHOUSE_HOST=default
    CLICKHOUSE_PORT=default
    CLICKHOUSE_USER=default
    CLICKHOUSE_PASSWORD=default
    CLICKHOUSE_DATABASE=default

    REDIS_HOST={CACHE_HOST}:6379
    REDIS_DATABASE=0
    REDIS_PASSWORD={CACHE_PASSWORD}

    USE_S3={USE_S3}
    S3_ACCESS_KEY_ID={ACCESS_KEY}
    S3_SECRET_KEY_ID={SECRET_KEY}


    BOOTSTRAP_BROKER={KAFKA_PREFIX}
    ACCESS_CONTROL_SERVICE=http://accesscontrol.{SERVICE_ENV}.svc.cluster.local
    ACCOUNT_SERVICE=http://account.{SERVICE_ENV}.svc.cluster.local

